org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
fabric_api_version=0.141.3+1.21.11
fabric_permissions_api_version=0.6.1
worldedit_version=7.4.0
luckperms_api_version=5.5

mod_version=0.1.7
maven_group=net.coreprotect
archives_base_name=coreprotect-fabric
